name: Frames-Streamly
version: '0.1.0.0'
synopsis: A Streamly layer for Frames I/O
description:
  More information is available in the <https://github.com/adamConnerSax/Frames-Streamly/blob/master/Readme.md
  readme>.'
category: Data
author: Adam Conner-Sax
maintainer: adam_conner_sax@yahoo.com
copyright: 2020 Adam Conner-Sax
license: BSD3
github: adamConnerSax/Frames-Streamly
extra-source-files:
- Changelog.md
- Readme.md
library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -O2
  - -fdicts-strict
  - -fmax-worker-args=16
  - -fspec-constr-recursive=16
  dependencies:
  - base >= 4.12.0 && < 4.15
  - exceptions >= 0.10.0 && < 0.11 
  - Frames >= 0.6 && < 0.8
  - primitive >= 0.7 && < 0.8
  - streamly >= 0.7 && < 0.8
  - text >= 1.2.3 && < 1.3
  - vinyl >= 0.12 && < 0.14
